name: CMake Windows

on: [ push, pull_request ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        platform: [ windows-2019,
                    windows-2022 ]
        architecture: [ Win32, x64 ]

    name: ${{ matrix.platform }} - ${{ matrix.architecture }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: List Generators
        run: cmake --help

      - name: Configure CMake
        run: cmake -A ${{ matrix.architecture }} -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}
