name: CMake Windows

on: [ push, pull_request ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        platform:
          - name: windows-2019
          - name: windows-2022
        compiler:
          - name: cl
          - name: g++
    name: ${{ matrix.platform.name }} - ${{ matrix.compiler.name }}
    runs-on: ${{ matrix.platform.name }}
    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        env:
          CXX: ${{ matrix.compiler.name }}
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}
