name: CMake Windows

on: [ push, pull_request ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ windows-2019, windows-2022 ]
        architecture: [ Win32, x64 ]

    name: ${{ matrix.platform }} - ${{ matrix.architecture }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -A ${{ matrix.architecture }} -B ${{ github.workspace }}/build -DDISABLE_RENDER_TESTS=ON

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

      - name: Test
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory: ${{ github.workspace }}/build/test
          run: ctest -C ${{ env.BUILD_TYPE }} --rerun-failed --output-on-failure
