name: CMake Linux GCC

on: [ push, pull_request ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-18.04, ubuntu-20.04 ]
        compiler: [ 8, 9, 10, 11 ]
        display: [ {
          name: X11,
          cmake: "",
          deps: "xorg-dev",
        },
          {
            name: Wayland,
            cmake: "-D GLFW_USE_WAYLAND=ON -D DISABLE_RENDER_TESTS=ON", # Headless wayland tests are not supported
            deps: "libwayland-dev libxkbcommon-dev wayland-protocols extra-cmake-modules",
          },
          {
            name: OSMesa (Headless),
            cmake: "-D GLFW_USE_OSMESA=ON",
            deps: "libosmesa6-dev",
          } ]
        exclude:
          # Ubuntu-18.04 only supports WaylandProtocols 1.13-1, which is less than the required 1.15
          - platform: ubuntu-18.04
            display:
              name: Wayland
    name: ${{ matrix.platform }} ${{ matrix.display.name }} - GCC ${{ matrix.compiler }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get install -y ${{ matrix.display.deps }} libgl1-mesa-dev gcc-${{ matrix.compiler }} g++-${{ matrix.compiler }}

      - name: Configure CMake
        env:
          CC: gcc-${{ matrix.compiler }}
          CXX: g++-${{ matrix.compiler }}
        run: cmake -B ${{ github.workspace }}/build -D CMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} ${{ matrix.display.cmake }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

      - name: Test
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory: ${{ github.workspace }}/build/test
          run: ctest -C ${{ env.BUILD_TYPE }} --rerun-failed --output-on-failure
