name: Code Coverage with Codecov

on: [ push, pull_request ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xorg-dev libgl1-mesa-dev lcov
      - name: Configure CMake with Coverage
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_FLAGS=--coverage

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory: ${{github.workspace}}/build/test
          run: ctest -C ${{env.BUILD_TYPE}}
      - name: lcov
        working-directory: ${{github.workspace}}/build
        run: |
          lcov -d core --capture --output-file coverage.info
          lcov --list coverage.info
      - name: Upload Coverage
        uses: codecov/codecov-action@v2
        with:
          working-directory: ${{github.workspace}}/build
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          files: coverage.info
