name: Code Coverage with Codecov

on: [ push, pull_request ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev xorg-dev lcov

      - name: Configure CMake with Coverage
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_FLAGS=--coverage

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory: ${{github.workspace}}/build/src
          run: |
            ctest -C ${{env.BUILD_TYPE}}
            lcov --directory ${{github.workspace}}/build/src --capture --output-file coverage.info
            lcov --list coverage.info

      - name: Upload Coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          files: coverage.info
